name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: unmango/actions/setup-nix@3ec4ed5a6af9c00f6a39e079df488573c77ebda6 # v1.0.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build schema
        run: |
          out=$(nix build .#pulumi-components-schema --print-out-paths)
          schema=$(find "$out" -name schema.json | head -n1)
          echo "SCHEMA_PATH=$schema" >> "$GITHUB_ENV"

      - name: Attach schema to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.ref_name }}" "$SCHEMA_PATH"
